name: twilio_conversations
description: A flutter plugin for Twilio Conversations.
version: 0.1.0
homepage: https://gitlab.com/twilio-flutter/conversations
repository: https://gitlab.com/twilio-flutter/conversations
issue_tracker: https://gitlab.com/twilio-flutter/conversations/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^1.10.9
  enum_to_string: ^2.0.1
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_conversations
        pluginClass: TwilioConversationsPlugin
      ios:
        pluginClass: TwilioConversationsPlugin
